# Copyright 2014-2015 by Cloudsoft Corporation Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

id: dockerfile-mysql
name: "Docker Hub MySQL Application"
origin: "https://registry.hub.docker.com/_/mysql/"
locations:
- my-docker-cloud
services:
- type: brooklyn.entity.container.docker.application.VanillaDockerApplication
  id: mysql
  name: "MySQL"
  brooklyn.config:
    docker.dockerfile.url:
      "https://s3-eu-west-1.amazonaws.com/brooklyn-clocker/mysql-5.6.tgz"
    docker.container.environment:
      MYSQL_ROOT_PASSWORD: "s3cr3t"

# mysql-5.6.tgz contains ./docker-entrypoint.sh and ./Dockerfile from GitHub
# https://github.com/docker-library/mysql
