apiVersion: v1
kind: ReplicationController
metadata:
  name: openshift-origin
  namespace: openshift
  labels:
    app: openshift-origin
    name: openshift-origin-replicationcontroller
spec:
  replicas: 1
  selector:
    app: openshift-origin
  template:
    metadata:
      labels:
        app: openshift-origin
    spec:
      containers:
        - args:
            - "start"
            - "master"
            - "--kubeconfig=/kubeconfig"
            - "--config=/config/master-config.yaml"
          image: "openshift/origin:v${config['openshift.version']}"
          name: origin
          env:
            - name: KUBECONFIG
              value: "/kubeconfig"
          ports:
            - containerPort: ${config['openshift.master.port']?c}
              name: openshift
          volumeMounts:
            - mountPath: "/config"
              name: config
              readOnly: true
            - mountPath: "/kubeconfig"
              name: kubeconfig
          #readinessProbe:
          #  httpGet:
          #    path: "/healthz/ready"
          #    port: ${config['openshift.master.port']?c}
          #    scheme: ${config['openshift.master.protocol']}
          #  initialDelaySeconds: 15
          #  timeoutSeconds: 1
          #livenessProbe:
          #  httpGet:
          #    path: "/healthz"
          #    port: ${config['openshift.master.port']?c}
          #    scheme: ${config['openshift.master.protocol']}
          #  initialDelaySeconds: 15
          #  timeoutSeconds: 1
      volumes:
        - name: config
          secret:
            secretName: openshift-config
        - name: kubeconfig
          hostPath:
            path: "/etc/kubernetes/kubeconfig"
