id: kubernetes
name: "Kubernetes Cluster"
description: |
  Includes built-in etcd discovery cluster and TLS protected Docker.

  Deploys on CentOS 7 VMs in SoftLayer, on a single VLAN segment.

location:
  jclouds:softlayer:
    region: ams01
    identity: xxxxxxxx
    credential: XXXXXXXX
    privateKeyFile: ~/.ssh/softlayer.pem
    customizers:
      - $brooklyn:object:
          type: org.apache.brooklyn.location.jclouds.softlayer.SoftLayerSameVlanLocationCustomizer
          brooklyn.config:
            softlayer.vlan.scopeUid: "kubernetes"

services:
  - type: kubernetes-cluster-application
    id: kubernetes
    name: "kubernetes"
    brooklyn.config:
      kubernetes.debug: true
      kubernetes.version: 1.4.5
      start.timeout: 30m
      kubernetes.master.size: 2
      kubernetes.initial.size: 4
      kubernetes.max.size: 16
      etcd.initial.size: 3
      kubernetes.apiserver.port: 8000
      kubernetes.scaling.cpu.limit: 0.80
      kubernetes.recovery.stabilizationDelay: 30s
      kubernetes.recovery.failOnRecurringFailuresInThisDuration: 300000
      docker.recovery.stabilizationDelay: 30s
      docker.recovery.failOnRecurringFailuresInThisDuration: 5m
      kubernetes.pod.cidr: "10.250.0.0/16"
      kubernetes.minRam: 10g
      kubernetes.minCores: 4
      provisioning.properties:
        minRam: 2g
        minCores: 1
