apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: kube-system
  labels:
    app: prometheus
    name: prometheus-service
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
    - name: prometheus
      protocol: TCP
      port: 9090
      nodePort: 30900
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  namespace: kube-system
  labels:
    app: prometheus
    name: prometheus-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: quay.io/prometheus/prometheus:v1.1.3
        name: prometheus
        command:
        - "/bin/prometheus"
        args:
        - "-config.file=/etc/prometheus/prometheus.yml"
        - "-storage.local.path=/prometheus"
        - "-storage.local.retention=24h"
        ports:
          - name: web
            containerPort: 9090
            protocol: TCP
        volumeMounts:
          - mountPath: "/prometheus"
            name: data
          - mountPath: "/etc/prometheus"
            name: config-volume
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 2500Mi
      volumes:
        - name: data
          emptyDir: {}
        - name: config-volume
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kube-system
data:
  prometheus.yml: |-
    global:
      scrape_interval: 30s
      scrape_timeout: 30s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets:
              - localhost:9090
      - job_name: 'kubernetes-cluster'
        kubernetes_sd_configs:
          - api_servers:
              - ${config['template.substitutions']['kubernetes_url']}
            basic_auth:
              username: prometheus
              password: pr0m3th3us
            role: apiserver
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - api_servers:
              - ${config['template.substitutions']['kubernetes_url']}
            basic_auth:
              username: prometheus
              password: pr0m3th3us
            role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - source_labels: [__meta_kubernetes_role]
            action: replace
            target_label: kubernetes_role
          - source_labels: [__address__]
            regex: (.*):10250
            replacement: ${r"${1}:10255"}
            target_label: __address__
      - job_name: 'kubernetes-service-endpoints'
        kubernetes_sd_configs:
          - api_servers:
              - ${config['template.substitutions']['kubernetes_url']}
            basic_auth:
              username: prometheus
              password: pr0m3th3us
            role: endpoint
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            action: replace
            target_label: __scheme__
            regex: (https?)
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+)(?::\d+);(\d+)
            replacement: ${r"${1}:${2}"}
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_service_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: kubernetes_name
